import re

from helpers import MIN_SCENARIOS, ROOT, load

LOCAL_LINK = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")


def test_readme_does_not_overclaim():
    text = (ROOT / "README.md").read_text(encoding="utf-8").lower()
    for phrase in ["bug-free", "error-free", "guaranteed", "best skills", "fully proven"]:
        assert phrase not in text


def test_generated_counts_are_documented():
    catalog = load("data/skills_catalog.json")
    scenarios = load("data/benchmark_scenarios.json")
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert f"- `{len(catalog)}` source-backed skill entries." in readme
    assert f"- `{len(catalog)}` written skill mirrors under `included/skills/`." in readme
    assert f"- `{len(catalog)}` compact agent-ready skill entrypoints under `included/agent-ready/`." in readme
    assert "- `34` repaired skill overlays under `included/repaired/skills/`" in readme
    assert "- `14` selected external benchmark method adapters with smoke artifacts." in readme
    assert f"- `{sum(1 for entry in catalog if entry['selected_subset'])}` selected repository entries." in readme
    assert f"- `{len({entry['category'] for entry in catalog})}` categories." in readme
    assert f"- `{len(scenarios)}` real-data scenario templates." in readme
    assert f"- Minimum `{MIN_SCENARIOS}` benchmark scenarios assigned per scenario-covered candidate." in readme
    assert "[Benchmark runner requirements](docs/benchmark-runner-requirements.md)" in readme
    assert "[Benchmark results](docs/benchmark-results.md)" in readme
    assert "[Runtime benchmark batch 01](docs/runtime-benchmark-batch-01.md)" in readme
    assert "[Runtime benchmark batch 02](docs/runtime-benchmark-batch-02.md)" in readme
    assert "[Runtime benchmark batch 03](docs/runtime-benchmark-batch-03.md)" in readme
    assert "[Local Markdown link failures](docs/local-markdown-link-failures.md)" in readme
    assert "[Repaired skill readiness](docs/repaired-skill-readiness.md)" in readme
    assert "[Objective benchmark methods](docs/objective-benchmark-methods.md)" in readme
    assert "[External benchmark adapter smoke](docs/external-benchmark-adapter-smoke.md)" in readme
    assert "[Skill risk findings](docs/skill-risk-findings.md)" in readme
    assert "[Immutable audit model](docs/immutable-audit-model.md)" in readme
    assert "[Included skill mirrors](included/skills/README.md)" in readme
    assert "[Agent-ready skills](included/agent-ready/README.md)" in readme
    assert "[Selected skills](docs/selected-skills.md)" in readme
    assert "Early alpha" in readme
    assert "priority entries from requested repositories" not in readme
    assert "AI-generated" not in readme
    assert "generated by AI" not in readme
    for forbidden in [
        "strmt7/simple_ai_bitcoin_trading_binance",
        "strmt7/ome-zarr-C",
        "strmt7/project_air_defense",
        "ZMB-UZH/omero-docker-extended",
    ]:
        assert forbidden not in readme
    assert not (ROOT / "docs" / "priority-skills.md").exists()


def test_benchmark_runner_requirements_are_explicit():
    text = (ROOT / "docs/benchmark-runner-requirements.md").read_text(encoding="utf-8")
    for phrase in [
        "actual websites",
        "delayed recall probes",
        "token usage before and after",
        "real public datasets",
        "runtime claim",
    ]:
        assert phrase in text


def test_documentation_local_links_resolve():
    docs = [ROOT / "README.md"]
    docs.extend(sorted((ROOT / "docs").rglob("*.md")))
    docs.extend([
        ROOT / "included" / "skills" / "README.md",
        ROOT / "included" / "agent-ready" / "README.md",
        ROOT / "included" / "selected" / "README.md",
    ])
    broken = []
    for path in docs:
        text = path.read_text(encoding="utf-8")
        for raw_target in LOCAL_LINK.findall(text):
            target = raw_target.strip().split("#", 1)[0].split("?", 1)[0]
            if not target or target.startswith(("http://", "https://", "mailto:")):
                continue
            if not (path.parent / target).exists():
                broken.append((path.relative_to(ROOT).as_posix(), raw_target))
    assert not broken


def test_agent_instructions_forbid_subagents():
    text = (ROOT / "AGENTS.md").read_text(encoding="utf-8").lower()
    for phrase in ["mandatory single-session rule", "do not spawn", "subagents", "one ai session only"]:
        assert phrase in text
    for phrase in [
        "separate work loops",
        "skill mirror loop",
        "artifact and test loop",
        "benchmark independence rule",
        "must not be counted as runtime benchmark passes",
        "repair overlay loop",
        "external benchmark adapter loop",
    ]:
        assert phrase in text
